# Generated by Django 4.1.4 on 2023-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
