# Generated by Django 4.1.4 on 2023-05-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_last_email_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_email_sent",
        ),
    ]
