# Generated by Django 4.1.9 on 2023-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_orders',
            field=models.ManyToManyField(related_name='orders', to='couriers.courierorder'),
        ),
    ]
